[package]
name = "sha1dir"
version = "0.1.1"
authors = ["David Tolnay <dtolnay@gmail.com>"]
edition = "2018"
license = "MIT OR Apache-2.0"
description = "Checksum of a directory tree"
repository = "https://github.com/dtolnay/sha1dir"
readme = "README.md"

[badges]
travis-ci = { repository = "dtolnay/sha1dir" }

[dependencies]
memmap = "0.7"
num_cpus = "1.0"
parking_lot = "0.9"
rayon = "1.0"
sha1 = "0.6"
structopt = "0.3"

[profile.release]
panic = "abort"

[package.metadata.docs.rs]
targets = ["x86_64-unknown-linux-gnu"]
